"""add_sentiment_and_topics_to_jobs

Revision ID: 990ff7f6f178
Revises: 7eea0e68429f
Create Date: 2026-09-15 08:36:01.932516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990ff7f6f178'
down_revision: Union[str, Sequence[str], None] = '7eea0e68429f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('sentiment', sa.String(length=50), nullable=True))
    op.add_column('jobs', sa.Column('topics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'topics')
    op.drop_column('jobs', 'sentiment')
    # ### end Alembic commands ###
